In [2]:
#array method 
import numpy as n
a=n.array([1,2,3])
b=n.array([1,2,3],dtype=float)
print(a)
print(b)

[1 2 3]
[1. 2. 3.]


In [6]:
#using arrange method
import numpy as n
a=n.arange(2,5)
print(a)

[2 3 4]


In [16]:
#2D
import numpy as n
x=n.array([n.arange(4),n.arange(4)])
x

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [14]:
a=n.array([1,2,3,4])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)

(4,)
int32
4
1


In [26]:
a=n.array([1,2,3,9])
b=n.array([4,5,6,2])
print(a+b)
print(a*b)
print(a.mean())

[ 5  7  9 11]
[ 4 10 18 18]
3.75


In [36]:
import numpy as n
n.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#2x3
n.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
n.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [42]:
#diving into 5 parts
n.linspace(1990,2025,5)

array([1990.  , 1998.75, 2007.5 , 2016.25, 2025.  ])

In [44]:
#indexing and slicing
a=n.array([[1,2,3],[4,5,6]])
print(a)
print(a[1,2])
print(a[:,2])

[[1 2 3]
 [4 5 6]]
6
[3 6]


In [48]:
import numpy as n
a=n.array([10,20,30,40,50])
print("Mean:",n.mean(a))
print("Median:",n.median(a))
data={
    "bill":[500,300,250,600,400,350],
    "service":["excellent","good","avg","poor","good","excellent"],
    "tip":[100,45,25,20,55,90]
}
print("Standard Deviation:",n.std(a))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [50]:
#reshape
import numpy as n
p=n.arange(6)
q=p.reshape([2,3])
q

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
#zeros 1D
import numpy as n
p=n.zeros(9)
p

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
#zero 2D
import numpy as n
p=n.zeros((3,3))
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
#ones-1D
import numpy as n
p=n.ones(9)
p

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
#zero 2D
import numpy as n
p=n.ones((3,3))
p

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
import numpy as n
a=n.array([1,2,3],dtype=float)
b=n.array([1,2,3],dtype=float)
c=sum(a,b)
c

array([7., 8., 9.])

In [67]:
import array
a=array.array('i',[1,2,3,4,5])
print(a)

array('i', [1, 2, 3, 4, 5])


In [12]:
import array
float_arr=array.array('f',[1.23,4.56,7.89])
print("Float Array:",float_arr)

Float Array: array('f', [1.2300000190734863, 4.559999942779541, 7.889999866485596])


In [6]:
import numpy as n
a=n.array([1,2],dtype=float)
b=n.array([3,4],dtype=float)
z=sum(a,b)
z

array([6., 7.])